// Code generated by apic. DO NOT EDIT.

package priority_backends

import (
	"bytes"
	"context"
	"fmt"
	"net/url"
	"text/template"

	"github.com/ngrok/ngrok-api-go"
)

type Client struct {
	apiClient *ngrok.Client
}

func NewClient(apiClient *ngrok.Client) *Client {
	return &Client{apiClient: apiClient}
}

// Create a new Priority backend
func (c *Client) Create(
	ctx context.Context,
	arg *ngrok.PriorityBackendCreate,
) (*ngrok.PriorityBackend, error) {
	var res ngrok.PriorityBackend
	var path bytes.Buffer
	if err := template.Must(template.New("create_path").Parse("/backends/priority")).Execute(&path, arg); err != nil {
		panic(err)
	}
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()
	bodyArg = arg

	if err := c.apiClient.Do(ctx, "POST", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Delete a Priority backend by ID. TODO what if used?
func (c *Client) Delete(
	ctx context.Context,
	id string,

) error {
	arg := &ngrok.Item{ID: id}
	var path bytes.Buffer
	if err := template.Must(template.New("delete_path").Parse("/backends/priority/{{ .ID }}")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()

	if err := c.apiClient.Do(ctx, "DELETE", apiURL, bodyArg, nil); err != nil {
		return err
	}
	return nil
}

// Get detailed information about a Priority backend by ID
func (c *Client) Get(
	ctx context.Context,
	id string,

) (*ngrok.PriorityBackend, error) {
	arg := &ngrok.Item{ID: id}
	var res ngrok.PriorityBackend
	var path bytes.Buffer
	if err := template.Must(template.New("get_path").Parse("/backends/priority/{{ .ID }}")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()

	if err := c.apiClient.Do(ctx, "GET", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// List all Priority backends on this account
func (c *Client) List(
	ctx context.Context,
	arg *ngrok.Page,
) (*ngrok.PriorityBackendList, error) {
	var res ngrok.PriorityBackendList
	var path bytes.Buffer
	if err := template.Must(template.New("list_path").Parse("/backends/priority")).Execute(&path, arg); err != nil {
		panic(err)
	}
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()
	queryVals := make(url.Values)
	if arg.BeforeID != nil {
		queryVals.Set("before_id", *arg.BeforeID)
	}
	if arg.Limit != nil {
		queryVals.Set("limit", *arg.Limit)
	}
	apiURL.RawQuery = queryVals.Encode()

	if err := c.apiClient.Do(ctx, "GET", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *Client) Iter(ctx context.Context) *Iter {
	return &Iter{
		client: c,
		ctx:    ctx,
		limit:  100,
		n:      -1,
	}
}

type Iter struct {
	client *Client
	ctx    context.Context
	n      int
	limit  int
	items  []ngrok.PriorityBackend
	err    error
}

func (it *Iter) Next() bool {
	// no more if there is an error
	if it.err != nil {
		return false
	}

	// are there items remaining?
	if it.n < len(it.items)-1 {
		it.n += 1
		return true
	}

	// fetch the next page
	lastItemID := ""
	if it.n > 0 {
		lastItemID = it.items[it.n].ID
	}
	fmt.Println("lastItemID", lastItemID, "n", it.n)
	resp, err := it.client.List(it.ctx, &ngrok.Page{
		BeforeID: ngrok.String(lastItemID),
		Limit:    ngrok.String(fmt.Sprintf("%d", it.limit)),
	})
	if err != nil {
		it.err = err
		return false
	}
	it.n = 0
	it.items = resp.Backends
	fmt.Println(len(it.items), it.items)
	return len(it.items) > 0
}

func (it *Iter) Item() *ngrok.PriorityBackend {
	return &it.items[it.n]
}

func (it *Iter) Err() error {
	return it.err
}

// Update Priority backend by ID
func (c *Client) Update(
	ctx context.Context,
	arg *ngrok.PriorityBackendUpdate,
) (*ngrok.PriorityBackend, error) {
	var res ngrok.PriorityBackend
	var path bytes.Buffer
	if err := template.Must(template.New("update_path").Parse("/backends/priority/{{ .ID }}")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()
	bodyArg = arg

	if err := c.apiClient.Do(ctx, "PATCH", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}
