// Code generated by apic. DO NOT EDIT.

package reserved_domains

import (
	"bytes"
	"context"
	"fmt"
	"net/url"
	"text/template"

	"github.com/ngrok/ngrok-api-go"
)

type Client struct {
	apiClient *ngrok.Client
}

func NewClient(apiClient *ngrok.Client) *Client {
	return &Client{apiClient: apiClient}
}

// Create a new reserved domain.
func (c *Client) Create(
	ctx context.Context,
	arg *ngrok.ReservedDomainCreate,
) (*ngrok.ReservedDomain, error) {
	var res ngrok.ReservedDomain
	var path bytes.Buffer
	if err := template.Must(template.New("create_path").Parse("/reserved_domains")).Execute(&path, arg); err != nil {
		panic(err)
	}
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()
	bodyArg = arg

	if err := c.apiClient.Do(ctx, "POST", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Delete a reserved domain.
func (c *Client) Delete(
	ctx context.Context,
	id string,

) error {
	arg := &ngrok.Item{ID: id}
	var path bytes.Buffer
	if err := template.Must(template.New("delete_path").Parse("/reserved_domains/{{ .ID }}")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()

	if err := c.apiClient.Do(ctx, "DELETE", apiURL, bodyArg, nil); err != nil {
		return err
	}
	return nil
}

// Get the details of a reserved domain.
func (c *Client) Get(
	ctx context.Context,
	id string,

) (*ngrok.ReservedDomain, error) {
	arg := &ngrok.Item{ID: id}
	var res ngrok.ReservedDomain
	var path bytes.Buffer
	if err := template.Must(template.New("get_path").Parse("/reserved_domains/{{ .ID }}")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()

	if err := c.apiClient.Do(ctx, "GET", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// List all reserved domains on this account.
func (c *Client) List(
	ctx context.Context,
	arg *ngrok.Page,
) (*ngrok.ReservedDomainList, error) {
	var res ngrok.ReservedDomainList
	var path bytes.Buffer
	if err := template.Must(template.New("list_path").Parse("/reserved_domains")).Execute(&path, arg); err != nil {
		panic(err)
	}
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()
	queryVals := make(url.Values)
	if arg.BeforeID != nil {
		queryVals.Set("before_id", *arg.BeforeID)
	}
	if arg.Limit != nil {
		queryVals.Set("limit", *arg.Limit)
	}
	apiURL.RawQuery = queryVals.Encode()

	if err := c.apiClient.Do(ctx, "GET", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *Client) Iter(ctx context.Context) *Iter {
	return &Iter{
		client: c,
		ctx:    ctx,
		limit:  100,
		n:      -1,
	}
}

type Iter struct {
	client *Client
	ctx    context.Context
	n      int
	limit  int
	items  []ngrok.ReservedDomain
	err    error
}

func (it *Iter) Next() bool {
	// no more if there is an error
	if it.err != nil {
		return false
	}

	// are there items remaining?
	if it.n < len(it.items)-1 {
		it.n += 1
		return true
	}

	// fetch the next page
	lastItemID := ""
	if it.n > 0 {
		lastItemID = it.items[it.n].ID
	}
	fmt.Println("lastItemID", lastItemID, "n", it.n)
	resp, err := it.client.List(it.ctx, &ngrok.Page{
		BeforeID: ngrok.String(lastItemID),
		Limit:    ngrok.String(fmt.Sprintf("%d", it.limit)),
	})
	if err != nil {
		it.err = err
		return false
	}
	it.n = 0
	it.items = resp.ReservedDomains
	fmt.Println(len(it.items), it.items)
	return len(it.items) > 0
}

func (it *Iter) Item() *ngrok.ReservedDomain {
	return &it.items[it.n]
}

func (it *Iter) Err() error {
	return it.err
}

// Update the attributes of a reserved domain.
func (c *Client) Update(
	ctx context.Context,
	arg *ngrok.ReservedDomainUpdate,
) (*ngrok.ReservedDomain, error) {
	var res ngrok.ReservedDomain
	var path bytes.Buffer
	if err := template.Must(template.New("update_path").Parse("/reserved_domains/{{ .ID }}")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()
	bodyArg = arg

	if err := c.apiClient.Do(ctx, "PATCH", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Detach the certificate management policy attached to a reserved domain.
func (c *Client) DeleteCertificateManagementPolicy(
	ctx context.Context,
	id string,

) error {
	arg := &ngrok.Item{ID: id}
	var path bytes.Buffer
	if err := template.Must(template.New("delete_certificate_management_policy_path").Parse("/reserved_domains/{{ .ID }}/certificate_management_policy")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()

	if err := c.apiClient.Do(ctx, "DELETE", apiURL, bodyArg, nil); err != nil {
		return err
	}
	return nil
}

// Detach the certificate attached to a reserved domain.
func (c *Client) DeleteCertificate(
	ctx context.Context,
	id string,

) error {
	arg := &ngrok.Item{ID: id}
	var path bytes.Buffer
	if err := template.Must(template.New("delete_certificate_path").Parse("/reserved_domains/{{ .ID }}/certificate")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()

	if err := c.apiClient.Do(ctx, "DELETE", apiURL, bodyArg, nil); err != nil {
		return err
	}
	return nil
}

// Detach the http endpoint configuration attached to a reserved domain.
func (c *Client) DeleteHTTPEndpointConfig(
	ctx context.Context,
	id string,

) error {
	arg := &ngrok.Item{ID: id}
	var path bytes.Buffer
	if err := template.Must(template.New("delete_http_endpoint_config_path").Parse("/reserved_domains/{{ .ID }}/http_endpoint_configuration")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()

	if err := c.apiClient.Do(ctx, "DELETE", apiURL, bodyArg, nil); err != nil {
		return err
	}
	return nil
}

// Detach the https endpoint configuration attached to a reserved domain.
func (c *Client) DeleteHTTPSEndpointConfig(
	ctx context.Context,
	id string,

) error {
	arg := &ngrok.Item{ID: id}
	var path bytes.Buffer
	if err := template.Must(template.New("delete_https_endpoint_config_path").Parse("/reserved_domains/{{ .ID }}/https_endpoint_configuration")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()

	if err := c.apiClient.Do(ctx, "DELETE", apiURL, bodyArg, nil); err != nil {
		return err
	}
	return nil
}
