// Code generated by apic. DO NOT EDIT.

package root

import (
	"bytes"
	"context"
	"net/url"
	"text/template"

	"github.com/ngrok/ngrok-api-go"
)

type Client struct {
	apiClient *ngrok.Client
}

func NewClient(apiClient *ngrok.Client) *Client {
	return &Client{apiClient: apiClient}
}

func (c *Client) Get(
	ctx context.Context,
	arg *ngrok.Empty,
) (*ngrok.RootResponse, error) {
	var res ngrok.RootResponse
	var path bytes.Buffer
	if err := template.Must(template.New("get_path").Parse("/")).Execute(&path, arg); err != nil {
		panic(err)
	}
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()

	if err := c.apiClient.Do(ctx, "GET", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}
