// Code generated by apic. DO NOT EDIT.

package endpoint_configurations

import (
	"bytes"
	"context"
	"fmt"
	"net/url"
	"text/template"

	"github.com/ngrok/ngrok-api-go"
)

// Endpoint Configuration managementAn
// (https://ngrok.com/docs/ngrok-link#api-endpoint-configurations)Endpoint
// Configuration describes
// a ngrok network endpoint instance.Endpoints are your gateway to ngrok features!

type Client struct {
	apiClient *ngrok.Client
}

func NewClient(apiClient *ngrok.Client) *Client {
	return &Client{apiClient: apiClient}
}

// Create a new endpoint configuration
func (c *Client) Create(
	ctx context.Context,
	arg *ngrok.EndpointConfigurationCreate,
) (*ngrok.EndpointConfiguration, error) {
	var res ngrok.EndpointConfiguration
	var path bytes.Buffer
	if err := template.Must(template.New("create_path").Parse("/endpoint_configurations")).Execute(&path, arg); err != nil {
		panic(err)
	}
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()
	bodyArg = arg

	if err := c.apiClient.Do(ctx, "POST", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Delete an endpoint configuration. This operation will fail if the endpoint
// configuration is still referenced by any reserved domain or reserved address.
func (c *Client) Delete(
	ctx context.Context,
	id string,

) error {
	arg := &ngrok.Item{ID: id}
	var path bytes.Buffer
	if err := template.Must(template.New("delete_path").Parse("/endpoint_configurations/{{ .ID }}")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()

	if err := c.apiClient.Do(ctx, "DELETE", apiURL, bodyArg, nil); err != nil {
		return err
	}
	return nil
}

// Returns detailed information about an endpoint configuration
func (c *Client) Get(
	ctx context.Context,
	id string,

) (*ngrok.EndpointConfiguration, error) {
	arg := &ngrok.Item{ID: id}
	var res ngrok.EndpointConfiguration
	var path bytes.Buffer
	if err := template.Must(template.New("get_path").Parse("/endpoint_configurations/{{ .ID }}")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()

	if err := c.apiClient.Do(ctx, "GET", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Returns a list of all endpoint configurations on this account
func (c *Client) List(
	ctx context.Context,
	arg *ngrok.Page,
) (*ngrok.EndpointConfigurationList, error) {
	var res ngrok.EndpointConfigurationList
	var path bytes.Buffer
	if err := template.Must(template.New("list_path").Parse("/endpoint_configurations")).Execute(&path, arg); err != nil {
		panic(err)
	}
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()
	queryVals := make(url.Values)
	if arg.BeforeID != nil {
		queryVals.Set("before_id", *arg.BeforeID)
	}
	if arg.Limit != nil {
		queryVals.Set("limit", *arg.Limit)
	}
	apiURL.RawQuery = queryVals.Encode()

	if err := c.apiClient.Do(ctx, "GET", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *Client) Iter(ctx context.Context) *Iter {
	return &Iter{
		client: c,
		ctx:    ctx,
		limit:  100,
		n:      -1,
	}
}

type Iter struct {
	client *Client
	ctx    context.Context
	n      int
	limit  int
	items  []ngrok.EndpointConfiguration
	err    error
}

func (it *Iter) Next() bool {
	// no more if there is an error
	if it.err != nil {
		return false
	}

	// are there items remaining?
	if it.n < len(it.items)-1 {
		it.n += 1
		return true
	}

	// fetch the next page
	lastItemID := ""
	if it.n > 0 {
		lastItemID = it.items[it.n].ID
	}
	fmt.Println("lastItemID", lastItemID, "n", it.n)
	resp, err := it.client.List(it.ctx, &ngrok.Page{
		BeforeID: ngrok.String(lastItemID),
		Limit:    ngrok.String(fmt.Sprintf("%d", it.limit)),
	})
	if err != nil {
		it.err = err
		return false
	}
	it.n = 0
	it.items = resp.EndpointConfigurations
	fmt.Println(len(it.items), it.items)
	return len(it.items) > 0
}

func (it *Iter) Item() *ngrok.EndpointConfiguration {
	return &it.items[it.n]
}

func (it *Iter) Err() error {
	return it.err
}

// Updates an endpoint configuration. If a module is not specified in the update,
// it will not be modified. However, each module configuration that is specified
// will completely replace the existing value. There is no way to delete an
// existing module via this API, instead use the delete module API.
func (c *Client) Update(
	ctx context.Context,
	arg *ngrok.EndpointConfigurationUpdate,
) (*ngrok.EndpointConfiguration, error) {
	var res ngrok.EndpointConfiguration
	var path bytes.Buffer
	if err := template.Must(template.New("update_path").Parse("/endpoint_configurations/{{ .ID }}")).Execute(&path, arg); err != nil {
		panic(err)
	}
	arg.ID = ""
	var (
		apiURL  = &url.URL{Path: path.String()}
		bodyArg interface{}
	)
	apiURL.Path = path.String()
	bodyArg = arg

	if err := c.apiClient.Do(ctx, "PATCH", apiURL, bodyArg, &res); err != nil {
		return nil, err
	}
	return &res, nil
}
