name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test / go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        go-version:
        - '1.18'
        - '1.19'
        - '1.20'
        - '1.21'
        - '1.22'
        - '1.23'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: go test -v -race -covermode=atomic ./...
